### ISSUE TITLE
Adding A Theme - Resume

### ISSUE THREAD

**Issue by hannylicious** [lektor/lektor-themes#1]
Per the documentation I'm opening this issue to add a new theme.

The theme can be found here: [https://github.com/hannylicious/lektor-theme-resume](https://github.com/hannylicious/lektor-theme-resume)

A working example of this can be found here: [https://hannylicious.github.io/lektor-theme-resume/](https://hannylicious.github.io/lektor-theme-resume/) 

*Edit: would you prefer this as a pull-request adding my theme as a submodule?

**Comment by nixjdm** [comment]
It looks good! I've added it to the repo. Thanks!

**Comment by nixjdm** [comment]
Is [this](https://twitter.com/hannylicious) you? Want a tweet?

**Comment by hannylicious** [comment]
That is in fact me! If you feel like tweeting - go for it! 👍
